trigger:
  - master

pool:
  vmImage: 'ubuntu-latest'
  
variables:
 - group: dev_portal

resources:
  repositories:
    - repository: templates
      type: github
      name: nkbali/sharedpipeline
      endpoint: github.com_nkbali

jobs:
  - template: shared.yml@templates  # Template reference